#ifndef PINS_H
#define PINS_H

// motor pins

// TODO: the input pins need to be correctly ordered

// left front
#define MOTOR_LEFT_FRONT_ENABLE 10
#define MOTOR_LEFT_FRONT_INPUT_1 11
#define MOTOR_LEFT_FRONT_INPUT_2 12

// left rear
#define MOTOR_LEFT_REAR_ENABLE 13
#define MOTOR_LEFT_REAR_INPUT_1 14
#define MOTOR_LEFT_REAR_INPUT_2 15

// right front
#define MOTOR_RIGHT_FRONT_ENABLE 21
#define MOTOR_RIGHT_FRONT_INPUT_1 20
#define MOTOR_RIGHT_FRONT_INPUT_2 19

// right rear
#define MOTOR_RIGHT_REAR_ENABLE 16
#define MOTOR_RIGHT_REAR_INPUT_1 17
#define MOTOR_RIGHT_REAR_INPUT_2 18

// all enable
#define ALL_MOTOR_ENABLE_MASK ((1 << MOTOR_LEFT_FRONT_ENABLE) | (1 << MOTOR_LEFT_REAR_ENABLE) | (1 << MOTOR_RIGHT_FRONT_ENABLE) | (1 << MOTOR_RIGHT_REAR_ENABLE))

// all input
#define ALL_MOTOR_INPUT_MASK ((1 << MOTOR_LEFT_FRONT_INPUT_1) | (1 << MOTOR_LEFT_FRONT_INPUT_2) | (1 << MOTOR_LEFT_REAR_INPUT_1) | (1 << MOTOR_LEFT_REAR_INPUT_2) | (1 << MOTOR_RIGHT_FRONT_INPUT_1) | (1 << MOTOR_RIGHT_FRONT_INPUT_2) | (1 << MOTOR_RIGHT_REAR_INPUT_1) | (1 << MOTOR_RIGHT_REAR_INPUT_2))

#endif // PINS_H
